name: mtpaint-casept
version: '3.49.12'
summary: Easily create pixel art and manipulate digital photos. Unofficial snap.
description: |
  mtPaint is a painting program which Mark Tyler developed from scratch so he could easily create pixel art and manipulate digital photos.
  It uses the GTK+ toolkit (version 1 or 2) and runs on PC's via the GNU/Linux or Windows operating systems. Due to its efficient design it can run on older PC hardware (e.g. a 200MHz CPU and 16MB of free RAM).
  mtPaint is free software, which means you are able to freely use, modify and distribute it according to the GNU General Public License.
  Currently mtPaint is maintained by Dmitry Groshev.



apps:
  mtpaint:
    command: desktop-launch $SNAP/bin/mtpaint
    plugs: [x11, opengl, home, optical-drive, removable-media]


grade: stable 
confinement: strict

parts:
  mtpaint: 
    plugin: autotools
    source: https://github.com/wjaguar/mtPaint.git
    source-commit: 6aed1b0441f99055fc7d475942f8bd5cb23c41f8
    build-packages:
      - build-essential
      - zlib1g-dev
      - libpng12-dev
      - libjpeg-dev
      - libtiff5-dev
      - libgif-dev
    after: [desktop-gtk2]
